### ISSUE TITLE
LUA Error in Login

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#154]
Still getting this issue with Grail:

Message: Interface\AddOns\Grail\Grail.lua:8290: script ran too long
Time: Thu Mar 19 21:18:15 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:8290: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:8290: in function `NPCName'
[string "@Interface\AddOns\Grail\Grail.lua"]:9719: in function `_RawNPCLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:8242: in function `NPCLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:9374: in function <Interface\AddOns\Grail\Grail.lua:9362>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:5883: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:1386: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:10580: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:11166: in function <Interface\AddOns\Grail\Grail.lua:11166>

Locals:

**Comment by smaitch** [comment]
Yes, some people get this and it seems when they:

/dump Grail.timings

It turns out their startup time is something ridiculous like 16000 milliseconds.  I have never been able to get startups to be that slow.

The problem is not in one specific place based on the reports, but in general trying to process the initial information.  I am trying to figure out ways to make that processing faster, but I am still  unsure why some people get startup times that are four times as slow as my worst startups.

**Comment by smaitch** [comment]
Can you try the latest version of Grail from GitHub to see if it helps?

**Comment by Wyr3d** [comment]
Sure I'll give it a shot. I also got this lua error on my current build on log in - in case you haven't fixed it on the GitHub one:

Message: Interface\AddOns\Grail\Grail.lua:3642: attempt to index field '?' (a nil value)
Time: Thu Mar 26 01:41:44 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:3642: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:3642: in function `_LearnWorldQuest'
[string "@Interface\AddOns\Grail\Grail.lua"]:3513: in function `_AddWorldQuests'
[string "@Interface\AddOns\Grail\Grail.lua"]:2075: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:10580: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:11166: in function <Interface\AddOns\Grail\Grail.lua:11166>

Locals:

**Comment by solitha** [comment]
With release 109... keep having to back up to 106, because breadcrumb notifications break with this error.

`1x Grail\Grail-109.lua:4437: script ran too long
[string "@Grail\Grail-109.lua"]:4437: in function `_NPCsMatch'
[string "@Grail\Grail-109.lua"]:4453: in function <Grail\Grail.lua:4441>
[string "=(tail call)"]: ?
[string "@Grail\Grail-109.lua"]:4686: in function `_CleanLearnedDatabase'
[string "@Grail\Grail-109.lua"]:4741: in function `?'
[string "@Grail\Grail-109.lua"]:1591: in function `?'
[string "@Grail\Grail-109.lua"]:10634: in function `_Tooltip_OnEvent'
[string "@Grail\Grail-109.lua"]:11220: in function <Grail\Grail.lua:11220>

Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Grail\Grail.lua:9241
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Grail\Grail.lua:7105
 totalRawNPCLocations = 15412.295626
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Grail\Grail.lua:9848
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Grail\Grail.lua:3401
 QuestLocationsAccept = <function> defined @Grail\Grail.lua:9399
 IsAvailable = <function> defined @Grail\Grail.lua:7087
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Grail\Grail.lua:6792
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Grail\Grail.lua:6820
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Grail\Grail.lua:5203
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Grail\Grail.lua:8505
 _MarkQuestType = <function> defined @Grail\Grail.lua:5590
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Grail\Grail.lua:9573
 _ProcessServerBackup = <function> defined @Grail\Grail.lua:8930
 bitMaskQuestVariableLevel = 255
 MeetsRequirementGroup = <function> defined @Grail\Grail.lua:8086
 _EvaluateCodeAsPrerequisite = <function> defined @Grail\Grail.lua:6109
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Grail\Grail.lua:8171
 DoesNPCExist = <function> defined @Grail\Grail.lua:6074
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Grail\Grail.lua:3772
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Grail\Grail.lua:8358
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Grail\Grail.lua:3227
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Grail\Grail.lua:7652
 _HandleEventAchievementEarned = <function> defined @Grail\Grail.lua:6787
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Grail\Grail.lua:10036
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Grail\Grail.lua:7577
 _ContainsAliasNPC = <function> defined @Grail\Grail.lua:5811
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Grail\Grail.lua:10135
 QuestBreadcrumbs = <function> defined @Grail\Grail.lua:9235
 NPCName = <function> defined @Grail\Grail.lua:8310
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Grail\Grail.lua:10682
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Grail\Grail.lua:7988
 QuestOnAcceptCompletes = <function> defined @Grail\Grail.lua:9585
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Grail\Grail.lua:7139
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Grail\Grail.lua:8114
 questReputations`

**Comment by smaitch** [comment]
@solitha Can you please send me your Grail.lua saved variables file so I can try to debug using your data?

**Comment by solitha** [comment]
Sure. I'm downgraded to 106 at the moment; do I need to update first and log in or will my current file do?

**Comment by smaitch** [comment]
Technically your current file will do.  However, it may not be needed any more as I have just uploaded a Grail 110 and Wholly 079 to GitHub that I believe should improve the situation immensely.  If you could try those I would think this is no longer an issue.

**Comment by smaitch** [comment]
Grail 110 is released.  It should fix this issue.

**Comment by solitha** [comment]
Sorry I never got back on this... as I've said before I'm crud at Github. Had to wait for the update to hit Curse... but you seem to have nailed it and thank you for your work!
