### ISSUE TITLE
New L system

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#160]
Any chance of an explanation of the L system. I am not as young and quick as I was. Any help would be appreciated.
The new Ks seem to be the the old ones less the level part.

Thanks.

**Comment by smaitch** [comment]
Yes, the new K codes are only the bit values from the end of the old K codes.  The new L code is not actually meant for anyone to adjust as I have processes that do that.  But in any case the next Grail release has it documented as:
--		Lxxxxxxx	where xxxxxxx is an integer value that represented three parts of a quest's level added together
--			The old K value * 65536
--			The old L value * 256
--			The old N value * 1

Basically what used to happen was the K, L, N and M codes were read in an an integer was made from them by parsing the strings and turning them into numbers that were part of a large integer.  Instead of doing that, I am setting the integer values directly from the K, L and N codes.  This makes the file smaller and speeds up processing it a bit.  The M code is not included at the moment because it needs to be revisited.  It may be included in the future based on findings but the few quests that have M codes are processed just as they were in the past.

**Comment by Nerillida** [comment]
Thanks, I get it now.
