### ISSUE TITLE
Failed to process completed query results

### ISSUE THREAD

**Issue by Mindrust1** [smaitch/Grail#179]
https://i.imgur.com/o2qvyCN.png

The map shows quests that I've completed.

**Comment by smaitch** [comment]
Most likely this is caused because you are using a character with the same name as a character that had recorded many quests being done before.  Therefore, Grail had recorded all those quests being done, and when Blizzard API returns a radically different value, Grail panics.  The reason this check Is in place is because in the past Blizzard API has had problems and Grail would abandon overwriting its information because it could not trust the Blizzard API.  If this is the case and you are reusing a character name, the only real workaround is to remove the per-character saved variables for Grail.  If this is not the case, I am unsure why the Blizzard API nowadays is being finicky.

**Comment by Nerillida** [comment]
There's the slash command to clear data, I use that since you added it.

/grail eraseAndReloadCompletedQuests => reloads the completed quest list from Blizzard erasing the current list

**Comment by smaitch** [comment]
One assumes this is resolved as no new information received from the OP.
