### ISSUE TITLE
Classic - AQ "holiday"

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#201]
July 28

Thanks

**Comment by smaitch** [comment]
The question is how to determine that the event has come to a close.  I.e., programmatically detecting the event is desired because we do not want to release a version of Grail that knows it started, and then have to release a version of Grail that knows it has ended when we see that it has ended in game.

**Comment by Nerillida** [comment]
Difficult as it'll be different on each realm. Maybe Blizzard exposes some value, I have no idea.
Maybe you'll just have to leave ut open until they're all closed.
My idea would be to have a simple additional file with each realm's status that can be updated as and when.

**Comment by Nerillida** [comment]
Also, the event has phases. Since you have run out of holiday codes, not sure how you will handle this.

**Comment by Nerillida** [comment]
I have tried to fix the conflict though it seems to still have one even though the code is identical

**Comment by Nerillida** [comment]
All dealt with
