### ISSUE TITLE
NPC ID generation

### ISSUE THREAD

**Issue by NERON** [smaitch/Grail#227]
Hi. I'm trying to add new NPCs and quests for Shadowlands...But i don't understand how keys for G array generated in Grail-NPCs. 

- Keys < 0: World Quests
- Keys that have 1000000 + gameobject ID: gameObjects
- Keys that have 100000000 + itemID: items
- Keys 3000000 to 4000000 NPC aliases generated by Grail

But we also have keys that 5000000 ..to 7000000. Why we have such range?  How gaps generated between keys (593805,593822,594429 this is sequence keys, for example..)

**Comment by smaitch** [comment]
The 5... ones were manually created a long while ago and were basically created from using the original NPC ID with a new location.  Then life became more complicated because some NPCs have more then two locations.  So, that is where the 7... values come from.  Basically Grail now creates new locations in the Grail.lua saved variables file using the 3... range and when that file is submitted, those values get translated to the proper 7... range values based on what already exits.  The same type of thing now happens for world quests using the Grail that is on GitHub.
I would suggest that the easiest way to add new quests and NPCs in Shadowlands is to use the latest Grail from GitHub, and just play as you would normally.  Then submit the Grail.lua saved variables file via email, a ticket, etc. and I can process it to have any new things you have found added to the release which will then be updated on GitHub until a new release is made to the public.
