### ISSUE TITLE
Incorrect quest levels in Grail

### ISSUE THREAD

**Issue by Zathriam** [smaitch/Grail#242]
Since the shadowlands pre-patch the zones and quests in them have had their level squished enabling people to level in whatever expansions they prefer.
The quest levels in the Grail db does not reflect this, making the integration with Wholly not work properly.
Checking the option in Wholly to display "High level" quests works around this, somewhat at least, but the markers displayed on the map are incorrect in colour/icon and possibly other ways.

I am currently working my way through the Legion and BfA content for the first time, so having no previous knowledge about thse expansion, I can't say for sure how many % it is that's not functioning.

These are ofc the latest releases of both Grail and Wholly.

**Comment by yoshimo** [comment]
Tables would be here:
https://shadowlands.wowhead.com/news=317295/level-squish-in-shadowlands-what-level-will-you-be-after-the-squish

Quest Level scaled before but not every quest goes the full way from 1-60.

**Comment by smaitch** [comment]
The problem is I cannot automatically determine quest levels with a good degree of confidence.  There are return values in game but for scaling quests they are based on the level of the character getting the quest, but there does not seem to be a way to know for sure that it is a scaling quest.  For other quests, the levels are fixed (verified e.g., with a level 51 and a level 57 getting the same quest and it reports level 51).

**Comment by smaitch** [comment]
Basic information about quest levels has been updated in the latest Grail in GitHub (114).  There are still some quests that are not set properly, but most are.
