### ISSUE TITLE
WOTLK

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#300]
Does it make sense to keep data separate per classic expansion in case they change quests on one expansion level but not the other?
Should we keep the data the same until the shattering?

**Comment by smaitch** [comment]
The reason why we have Classic and BCC is because they are different enough to warrant the separation.  However, to make further files separate we will cause the addon to increase in size, perhaps unnecessarily.  For example, if the majority of data for a new expansion is the same and all that is needed is a few items of difference the size increase for duplicated data may not be worth it.  In any case, we would need to know how to differentiate between expansions if there are differences.  So, if WOTLK actually is separate from BCC (and both can survive on their own) then we need detection routines and to choose whether its data should be separate.  If, however, WOTLK is just BCC we might only need to make changes based on whether someone is in that middle period where WOTLK is in beta and BCC is in production.

**Comment by yoshimo** [comment]
ptr switched to 3.4 and i was wondering if we should start with bc data as a foundation instead of recording from scratch and missing out on data because people skip the bc part when playing wotlk classic :)

**Comment by smaitch** [comment]
I think we should start with a foundation of data, and be able to correct as needed.  Starting from scratch is not appropriate since the number of people that would do that are limited as you suggest.

**Comment by yoshimo** [comment]
I think we should have one file per expansion for this classic stuff
If a new expansion comes out, we clone the existing file and rename it.
Therefore we have a non-empty file with basic data for the new expansion, wotlk in this case and on the other hand have the opportunity to adjust data in case blizzard decides to retro-actively change old quests.

**Comment by smaitch** [comment]
So for the latest push I have three TOC files: <retail>, _Vanilla, and _Wrath.  I am not sure how one could be in a _TBC environment so I just removed it.  I have also separated out the quests and npcs into a _classic_ and a _classic_wrath_, though I have not separated out the localized files with the quest names and npc names.
