### ISSUE TITLE
DragonFlight Beta observations

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#322]
We have new factions like https://www.wowhead.com/beta/factions/dragonflight/maruuk-centaur 
where your reputation level unlocks rewards and quests.

We also have temporary events that make quests and npcs available including dailies and repeatables  like

![grafik](https://user-images.githubusercontent.com/17909/202737768-f22e7c49-87ca-4310-b091-3363e84cee48.png)
****

**Comment by yoshimo** [comment]
Quite a few chests and achievements need renown and quests to unlock, maybe we should do this like handynotes_dragonflight. Show them but mark the requirements a bit more differentiated

**Comment by yoshimo** [comment]
Things are unlocked account wide very often, so we need to keep in mind that once you get the campaign done on the first character, everything is up for a change

https://www.wowhead.com/beta/quest=66221/moving-on#criteria-of
https://www.wowhead.com/beta/achievement=16326/hidden-account-campaign-complete

**Comment by yoshimo** [comment]
Renown is important so i think we should mark renown level changes in the log

**Comment by smaitch** [comment]
It is going to be interesting to see how each of the renown levels maps to each of the quests.  I have already seen it a couple times, but cannot be totally sure of the mapping.

**Comment by yoshimo** [comment]
the renown menu of each faction mentions some hints yes

**Comment by yoshimo** [comment]
Around quests like https://www.wowhead.com/quest=72524/basic-climbing-gear there are research trees that unlock new skills and new questlines.
They require dragon isle supplies and other things to be researched and unlocked.
That is something we have to look at as well.

**Comment by yoshimo** [comment]
https://www.wowhead.com/beta/achievement=16409/lets-get-quacking
You can only do one quest of them each week, tracked by

```/dump C_QuestLog.IsQuestFlaggedCompleted(70872)```

so we probably need to add "!completed" as a condition to the duckling quests.
Verify, like with other quests and achivements with Handynotes by Zarillion,
https://github.com/zarillion/handynotes-plugins/blob/master/plugins/10_Dragonflight/zones/waking_shores.lua in this case

**Comment by smaitch** [comment]
The portals have been integrated and seem to be working.  Of course we need to verify the trigger quest has the proper renown, but the rest of the mechanism seems to work.  The Ruby Feast quests are integrated.  The Tarjin's Tales quests are being integrated but I think the mechanism is understood and handled well enough.  I haven't put requirements for the cartographer or climbing quests in place yet, but will do that over time.  For completing the campaign I am currently using quest 67030 instead of the achievement, but that could change in the future.  The major problem I have at the moment is detecting renown at the account level.  In other words, I understand when a quest is available because the account has reached that renown level versus the player reaching it.  However, I cannot figure out how to determine whether the account has reached a specific renown level.  I had thought perhaps a hidden quest, but could not find a pattern.  The easiest I was trying with is Maruuk at renown level 4 because the Aylaag quests are available then.  I have marked Grail indicating it needs account-wide renown, but have no way to really detect that versus the player's own renown.
