### ISSUE TITLE
Grail shows quests as finished

### ISSUE THREAD

**Issue by Meridyna** [smaitch/Grail#336]
Hey there, got a bug, I think.
My wife and I are twinking a bit. Two weeks ago we were questing in Silverpine Forest, we did all the quests and moved on. 
Today we realized we never see any quests on the world map. Switching to another map there are all the map pins.
I opened Wholly and all the quests were finished ...

I googled a bit, but everyone only had the problem when using characters with the same name. We have new names, new classes, new races. Only they are all on horde.

I deleted all the saved variables (through curseforge), reinstalled grail and ... nothing changed.
Even on older character who were never in that area the quests don't have any on the map. Only in other areas.

Attached is a screenshot from the older Character who never was in Silverpine Forest. The other one is the same, but I only quested about half the mal (left) with my other one (from two weeks ago)

![HillsbradFoothills](https://user-images.githubusercontent.com/63635915/231256518-b1452860-aca7-4a6b-a2c3-02a47e986547.PNG)
![SilverpineForest](https://user-images.githubusercontent.com/63635915/231256534-e88c4b06-44c5-4a9f-aa96-f5dbad2512e7.PNG)

**Comment by Wyr3d** [comment]
"I deleted all the saved variables (through curseforge), reinstalled grail and ... nothing changed."

To remove character data, you would need to navigate to your WoW installation, then the game version (_classic_ for WotLK, _classic_era_ for Classic Vanilla, _retail_ for retail) then select the WTF folder, then account folder, then the name of your account, and then the server you are playing on. Here is where your character data is stored.

Select the forlder for the offending character, then SavedVariables, and delete the all the Grail files (Grail.LUA, Grail.lua.BAK) and this will force the information to repopulate. The When files (Grail-When.LUA, and Grail-When.lua.BAK) only deal wih completion dates, so you should not need to delete these, but you could try removing them temporarily if the issue persists. 

There is no need to delete the Wholly files (Wholly.LUA, Wholly.lua.BAK) as these only deal with the interface, but you could try deleting these too if something has bugged out with the settings.

TBH though, this might not do anything for you, since you state the char names were fresh..

**Comment by smaitch** [comment]
You can do the slash command:

/grail eraseAndReloadCompletedQuests

That should erase all the quests marked as complete for your character and reload them from the server.

If you have reused a name, even across factions, it will use that old name.  Only if you are on a different server will the names being the same be ok.

**Comment by Meridyna** [comment]
No, unique name on this server and never played with a charakter with the same name, this map.

I deleted the Grail Files for my Character (copy&pasted it on my desktop, all grail, grail-when and wholly .LUA and .lua.BAK files then deleted those in my saved variables) and nothing.

I also tried the slash commands and nothing changed.
But I'm thinking about one thing:
Could it be, that there are no "free and independent" sidequests in silverpine forest? Checked with BtWQuests and it seems like it.
Then I might remember it wrong from last time...
If so, then I'm sorry for bothering you :)
