### ISSUE TITLE
Quests are broken. (Classic ERA)

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#379]
Nothing is showing up at all.

Wholly interface shows the sections for  Continent, Class, Profession etc but nothing is listed anywhere. The only information that shows is reputation if this is enabled. Tested on both the new anniversary servers, and the original ERA servers

**Comment by Wyr3d** [comment]
![empty](https://github.com/user-attachments/assets/964c7aa5-f8ba-40b2-a0f0-0ad0554dab0f)

**Comment by Wyr3d** [comment]
As you can see above, the Continent section has no dropdown for the zones. Nothing is showing

**Comment by smaitch** [comment]
This should now be corrected with the latest code checked in here.  Basically what was happening was the quests and NPCSs were not being loaded because Blizzard changed the release version and there was a check in the file against release version.  With the new code, the check is not made against the release version, but on the system that is running and should be more resilient to Blizzard release updates.

**Comment by Wyr3d** [comment]
Copied and pasted the new set of Grail files, and can confirm Wholly/Grail is working again on Classic ^^
