### ISSUE TITLE
CLASSIC - Deeprun Tram NPCs

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#65]
Classic
*** Regading Deeprun Tram NPCs ***

G[12997]={'947:0.00,0.00'} -- Monty

G[13018]={'947:0.00,0.00'} -- Nipsy

These are in the Tram instance and probaly could do with an external marker as discussed.

The Stormwind entrance is 1453:63.83,8.34. the Ironforge entrance at 1455:76.08,51.19

If you would only like one "entrance", the Ironforge end starts both quests.

This is also where a location comment in the form of

G[12997]={'1455:76.19,51.00','Deeprun Tram Ironforge end'} -- Monty
G[13018]={'1453:51.77,12.08','Deeprun Tram Stormwind end'}  --Nipsy

as well as the entrance(s) information.

**Comment by smaitch** [comment]
I have added their "dungeon" locations for the next release of Grail.  Both the quests have the map icon appear in Ironforge as long as the Wholly preference for dungeon quests appearing in outer map are set.  Unfortunately the link location is "Azeroth" and not Deeprun Tram because there is actually no map named Deeprun Tram.

**Comment by Nerillida** [comment]
Thanks
