### ISSUE TITLE
CLASSIC - minor items

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#67]

**Comment by Nerillida** [comment]
(1) the latest release, 102, is not tagged for classic so not showing in Twitch updater.
(2) the quests are not respecting the quest givers' alignment via map pins or Wholly tips.
(3) You may want to define two world events for Classic to mask quests, War Effort, and Gates Ahn Qiraj opening.
Thanks

**Comment by smaitch** [comment]
(1) Correct, it is not tagged as supporting Classic on curseforge, because it was an experiment to test Twitch.  With it marked for both Classic and Retail, Twitch was not showing the most recent version for Retail people.  I have no idea how to make Twitch look for Classic addons to be able to test that aspect.  Basically I believe Twitch is broken, and I created a case with them five days ago but they have not replied.
(2) That is not what I am seeing.  When I am Alliance all the quests in Mulgore do not appear on the map, and the Wholly quest panel shows those Mulgore quests as unavailable due to Faction, and the NPCs are in red in the Wholly quest panel tooltip.  Likewise with Horde and quests in Elwynn Forest.
(3) Do we know when these events are happening?

**Comment by Nerillida** [comment]
(3) No, but there are quite a few quests in that only occur during the War Effort. I thought it may be an idea to mask them. In my fork, I have used X as it seems unused by another event.

(2) Sorry, I overrated that, it's the mouse over items in Wholly's lists.

![Screen Shot 2019-10-02 at 19 19 15](https://user-images.githubusercontent.com/55858788/66070969-31f52200-e54a-11e9-873c-7133e728d898.png)

(1) As long as you're aware. 

Thank you again.

**Comment by smaitch** [comment]
The most recent release of Wholly and Grail have been released separately for Retail and Classic, thus allowing Twitch to get the right versions.  The latest version of Grail on GitHub marks quest factions with their quest giver factions.  A bogus AQ holiday has been added (code HQ) so we can support that event once we know when it happens.
