### ISSUE TITLE
CLASSIC - clear statuses 

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#71]
The command /grail clear statuses does not seem to work on classic.

Thanks.

**Comment by smaitch** [comment]
I cannot reproduce this problem.  I can see that when I do "/grail clearstatuses" I am clearing the statuses and causing the recomputation of the needed statuses to be done.
Do you have any more information that makes you think it is not working?

**Comment by Nerillida** [comment]
I tend to reuse character names. As an example Mapper is created and does priest quests. When I have enough values, I delete Mapper and create a new Mapper. This saves having to redefine all the other addons values. However, the new Mapper can not zero the quests. maybe that's not what clearstatuses was designed for. I had read it as recomputing the values with a blank slate. However, I am told thattheire is a discrepancy between the number recorded and the server reply. I have to delete the saved variables directly. 
Sorry to be a pain…

**Comment by smaitch** [comment]
That is the problem.  Grail sees the difference between what the server returns and what is already recorded, and decides to not change what has been recorded.  This is a holdover for when Blizzard actually had a flaky quest service.  This issue is not solved with clearing the statuses.  I think perhaps I will add a new command to wipe the recorded quests and load from Blizzard.

**Comment by Nerillida** [comment]
That would help my somewhat peculiar need.
Thanks.

**Comment by smaitch** [comment]
A new command has been added to Grail 103 which is now released.
